app = 'films-collection-app'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256'
  cpu_kind = 'shared'
  cpus = 1
